name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-go-code:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    name: Test Go Code (Go ${{ matrix.go }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Test Go Code
        run: go test -v -race ./...
